### ISSUE TITLE
Update for Zeek

### ISSUE THREAD

**Issue by weslambert** [weslambert/securityonion-misp#2]

**Comment by weslambert** [comment]
https://github.com/weslambert/securityonion-misp/pull/3/commits/fed05be85b9861c43c4f83d8ff98b5e8d9587d4a

https://github.com/weslambert/securityonion-misp/commit/78f1dc45327c29e706e2f91fe79e1c08564f361b

**Comment by weslambert** [comment]
@lat1tude - please test and let me know if you have any issues with the latest commits.  Thanks!

**Comment by lat1tude** [comment]
I have no issues at this time

**Comment by weslambert** [comment]
Excellent, thanks!
